### ISSUE TITLE
It always creates `.copier-answers.yml`, even when a template is not updatable

### ISSUE THREAD

**Issue by yajo** [KyleKing/copier-template-tester#24]
**Describe the bug**

When the template doesn't support updates, it shouldn't create a copier answers file.

However, CTT always creates it.

**To Reproduce**

I've got a template that is not updatable: https://gitlab.com/moduon/odoo-module-template

Clone it, enter the folder, run CTT 1.2.6.

**Expected behavior**

`.copier-answers.yml` shouldn't be created, just like normal Copier wouldn't.

**Comment by yajo** [comment]
Even worse, when you run the STR twice, Copier fails because the file is empty:

Starting Copier Template Tester for /var/home/yajo/prodevel/odoo-module-template
Note: If files were modified, pre-commit will report a failure.

```
Using `copier` to create: .ctt/defaults
/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier/vcs.py:179: DirtyLocalWarning: Dirty template changes included automatically.
  warn(
Traceback (most recent call last):
  File "/nix/store/l70fk640snxjzxjqdksrxwgqjvyqcbci-python3.11-copier-template-tester-1.2.6/bin/.ctt-wrapped", line 9, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "<@beartype(copier_template_tester.main.run_cli) at 0x7f8ff1270040>", line 11, in run_cli
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier_template_tester/main.py", line 65, in run_cli
    run(base_dir=args.base_dir, check_untracked=args.check_untracked)
  File "<@beartype(copier_template_tester.main.run) at 0x7f8ff1f83880>", line 45, in run
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier_template_tester/main.py", line 40, in run
    write_output(src_path=input_path, dst_path=base_dir / output_path, data=defaults | data)
  File "<@beartype(copier_template_tester._write_output.write_output) at 0x7f8fef0fb240>", line 57, in write_output
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier_template_tester/_write_output.py", line 114, in write_output
    copier.run_copy(str(src_path), dst_path, **kwargs)
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier/main.py", line 948, in run_copy
    with Worker(src_path=src_path, dst_path=Path(dst_path), **kwargs) as worker:
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier/main.py", line 218, in __exit__
    raise value
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier/main.py", line 949, in run_copy
    worker.run_copy()
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier/main.py", line 733, in run_copy
    self._ask()
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier/main.py", line 419, in _ask
    last=self.subproject.last_answers,
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/px3zbr30lbnmb3drlx5djwdd792l9vwz-python3-3.11.4/lib/python3.11/functools.py", line 1001, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/wahz556rkmzw6i9302r15mzf0wj03m8l-python3-3.11.4-env/lib/python3.11/site-packages/copier/subproject.py", line 66, in last_answers
    for key, value in self._raw_answers.items()
                      ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by KyleKing** [comment]
Oh cool, I didn't know copier could be used that way! I'll release an update when I have time later this week. The current CTT implementation always assumes the templates will be updated.

**Comment by yajo** [comment]
That's opt-in feature by the template publisher. When the `{{ _copier_conf.answers_file }}.jinja` file is found, then it declares that it supports updates.

FWIW there's a proposal to simplify this: https://github.com/copier-org/copier/issues/983

**Comment by KyleKing** [comment]
I have a fix, added new tests, and it seems to work when run locally for `[odoo-module-template](https://gitlab.com/moduon/odoo-module-template)`

```
> pre-commit run copier-template-tester
copier-template-tester...................................................Passed
```

Let me know if the new version is still causing issues!

**Comment by KyleKing** [comment]
FYI: the changes are in v2.0.0 of CTT: https://pypi.org/project/copier_template_tester/2.0.0
