### ISSUE TITLE
PermissionError on "Removing git created by copier" on windows if "git add ." is in the _tasks

### ISSUE THREAD

**Issue by sanzoghenzo** [KyleKing/copier-template-tester#34]
Hi there, first of all thank you very much for this tool!

**Describe the bug**

I'm on a windows 10 machine, and in my `copier.yaml` I initialize the git repository and stage the files:

```yaml
_subdirectory: template
# questionnaire here...
_tasks:
  - git init
  - git add .
```

The template renders correctly, the tasks run fine, but at the end I got this error:

```
Removing git created by copier git_path=<project dir>\.ctt\defaults\.git
Traceback (most recent call last):
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "%USERPROFILE%\.local\bin\ctt.exe\__main__.py", line 8, in <module>
  File "%USERPROFILE%\AppData\Roaming\uv\tools\copier-template-tester\lib\site-packages\copier_template_tester\main.py", line 67, in run_cli
    run(base_dir=args.base_dir, check_untracked=args.check_untracked)
  File "%USERPROFILE%\AppData\Roaming\uv\tools\copier-template-tester\lib\site-packages\copier_template_tester\main.py", line 44, in run
    write_output(src_path=input_path, dst_path=base_dir / output_path, data=defaults | data)
  File "%USERPROFILE%\AppData\Roaming\uv\tools\copier-template-tester\lib\site-packages\copier_template_tester\_write_output.py", line 144, in write_output
    shutil.rmtree(git_path)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 750, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 615, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 620, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "%USERPROFILE%\AppData\Local\Programs\Python\Python310\lib\shutil.py", line 618, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: '<project dir>\\.ctt\\defaults\\.git\\objects\\0a\\e48258d27f73e6d23157bc56d1e943e87a07b4' 
```

The problem is specific to windows, and there's a [rmtree example in the shutils documentation](https://docs.python.org/3/library/shutil.html#rmtree-example) that explains how to solve that:

```python
import os, stat
import shutil

def remove_readonly(func, path, _):
    "Clear the readonly bit and reattempt the removal"
    os.chmod(path, stat.S_IWRITE)
    func(path)

shutil.rmtree(directory, onexc=remove_readonly)
```

**To Reproduce**

- Use a windows machine
- create a template with `_tasks: ['git init', 'git add .']`
- run `ctt`

**Expected behavior**

the .git directory should be removed without errors.

**Comment by KyleKing** [comment]
Thanks for trying out CTT and leaving such a clear bug report!

I have added a Windows test to CI and cut a new release with the suggested fix (`2.1.4`). Please let me know if you run into any additional issues or if you have other feedback.
